name: Deploy to Pages

concurrency: production

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build & Deploy
        runs-on: ubuntu-lates
        environment:
            name: GitHub Pages
            url: https://timagribanov.com/mushroom-game
        
        steps:
            - name: Chekout the repo
              uses: actions/checkout@v4
        
            - name: Show repo contents
              run: ls -alR
            
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: '18'
            
            - name: Get yarn cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
              
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                path: ${{ steps.yarn-cache.outputs.dir }}
                key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                restore-keys: |
                    ${{ runner.os }}-yarn-
            
            - run: yarn install --frozen-lockfile
            
            - run: yarn build
              env:
                REACT_APP_GIT_SHA: ${{ github.SHA }}

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build